import streamlit as st
import pandas as pd
import plotly.express as px
from fpdf import FPDF
import io

# ১. ব্র্যান্ডিং ও স্টাইল
st.set_page_config(page_title="Super Tasty Food - Smart Dashboard", layout="wide")

st.markdown("""
    <style>
    .main { background-color: #0f1116; color: #ffffff; }
    .stMetric { background-color: #1a1c24; padding: 15px; border-radius: 12px; border-top: 4px solid #f39c12; }
    h1 { color: #f39c12; text-align: center; }
    </style>
    """, unsafe_allow_html=True)

st.title("🍎 Super Tasty Food - স্মার্ট সেলস ড্যাশবোর্ড")
st.markdown("<p style='text-align: center;'>Keshobpur, Jashore</p>", unsafe_allow_html=True)

# ২. সাইডবার: মার্কেটিং ইনপুট
st.sidebar.header("📊 মার্কেটিং এনালাইসিস")
usd_rate = st.sidebar.number_input("আজকের ডলার রেট (BDT)", value=125.0)
ad_spend_usd = st.sidebar.number_input("ফেসবুক অ্যাড স্পেন্ড (USD)", value=0.0)
ad_spend_bdt = ad_spend_usd * usd_rate

# ৩. স্মার্ট ডাটা হ্যান্ডলিং ফাংশন
def process_data(df):
    # প্রয়োজনীয় কলামের সম্ভাব্য নাম (Alias)
    mapping = {
        "মূল দাম": ["মূল দাম", "Cost", "Base Price"],
        "প্যাকেজিং খরচ": ["প্যাকেজিং খরচ", "প্যাকেজিং", "Packaging"],
        "ডেলিভারি (কোম্পানি)": ["ডেলিভারি (কোম্পানি)", "Delivery Co", "Delivery Cost"],
        "সেল প্রাইজ": ["সেল প্রাইজ", "Sale Price", "Selling Price"],
        "রিটার্ন রেট (Decimal)": ["রিটার্ন রেট (Decimal)", "Return Rate", "Return"],
        "কয়টা অর্ডার": ["কয়টা অর্ডার", "অর্ডার", "Orders", "Qty"]
    }
    
    # ডাইনামিকভাবে কলাম খুঁজে বের করা বা নতুন তৈরি করা
    for final_name, aliases in mapping.items():
        found = False
        for alias in aliases:
            if alias in df.columns:
                df[final_name] = pd.to_numeric(df[alias], errors='coerce').fillna(0)
                found = True
                break
        if not found:
            df[final_name] = 0.0
            
    # ক্যালকুলেশন
    df["মোট খরচ"] = (df["মূল দাম"] + df["প্যাকেজিং খরচ"] + df["ডেলিভারি (কোম্পানি)"]) * df["কয়টা অর্ডার"]
    df["মোট রেভিনিউ"] = df["সেল প্রাইজ"] * df["কয়টা অর্ডার"]
    df["এভারেজ লাভ"] = (df["মোট রেভিনিউ"] - df["মোট খরচ"]) * (1 - df["রিটার্ন রেট (Decimal)"])
    return df

# ৪. ডাটা ইনপুট
st.subheader("📥 ডাটা আপডেট করুন")
input_tab1, input_tab2 = st.tabs(["📋 ম্যানুয়াল/কপি-পেস্ট", "📂 CSV আপলোড"])

with input_tab1:
    # শুরুতে খালি টেবিল যা কপি-পেস্ট সাপোর্ট করে
    df_input = st.data_editor(pd.DataFrame(columns=["প্রোডাক্টের নাম", "মূল দাম", "প্যাকেজিং খরচ", "ডেলিভারি (কোম্পানি)", "সেল প্রাইজ", "রিটার্ন রেট (Decimal)", "কয়টা অর্ডার"]), num_rows="dynamic", use_container_width=True)

with input_tab2:
    uploaded_file = st.file_uploader("CSV ফাইল দিন", type="csv")
    if uploaded_file:
        df_input = pd.read_csv(uploaded_file)

# ৫. রিপোর্ট জেনারেশন ও ডিসপ্লে
if not df_input.empty:
    df_final = process_data(df_input)
    
    total_revenue = df_final["মোট রেভিনিউ"].sum()
    total_cost = df_final["মোট খরচ"].sum()
    net_profit = total_revenue - total_cost - ad_spend_bdt
    roas = total_revenue / ad_spend_bdt if ad_spend_bdt > 0 else 0

    # মেট্রিক কার্ডস
    st.divider()
    c1, c2, c3, c4 = st.columns(4)
    c1.metric("মোট রেভিনিউ", f"৳{total_revenue:,.0f}")
    c2.metric("অ্যাড খরচ (BDT)", f"৳{ad_spend_bdt:,.0f}")
    c3.metric("নিট লাভ (অ্যাড বাদে)", f"৳{net_profit:,.0f}")
    c4.metric("ROAS", f"{roas:.2f}x")

    # ৬. প্রফেশনাল পিডিএফ জেনারেটর (FPDF)
    def generate_pdf():
        pdf = FPDF()
        pdf.add_page()
        
        # হেডার: ব্র্যান্ডিং
        pdf.set_font("Arial", 'B', 18)
        pdf.cell(200, 10, txt="Super Tasty Food", ln=True, align='C')
        pdf.set_font("Arial", '', 10)
        pdf.cell(200, 8, txt="Location: Keshobpur, Jashore", ln=True, align='C')
        pdf.ln(10)
        
        # সামারি সেকশন
        pdf.set_font("Arial", 'B', 14)
        pdf.cell(200, 10, txt="Daily Sales Summary Report", ln=True)
        pdf.set_font("Arial", '', 12)
        pdf.cell(200, 8, txt=f"Total Revenue: BDT {total_revenue:,.2f}", ln=True)
        pdf.cell(200, 8, txt=f"Ad Spend (USD): {ad_spend_usd} (Rate: {usd_rate})", ln=True)
        pdf.cell(200, 8, txt=f"Ad Spend (BDT): {ad_spend_bdt:,.2f}", ln=True)
        pdf.cell(200, 8, txt=f"Net Profit: BDT {net_profit:,.2f}", ln=True)
        pdf.cell(200, 8, txt=f"ROAS: {roas:.2f}x", ln=True)
        
        # ফুটার
        pdf.ln(20)
        pdf.set_font("Arial", 'I', 8)
        pdf.cell(200, 10, txt="Generated by Super Tasty Food Smart Dashboard", ln=True, align='C')
        
        return pdf.output(dest='S').encode('latin-1', 'ignore')

    st.subheader("📊 বিস্তারিত রিপোর্ট")
    st.dataframe(df_final, use_container_width=True)

    # পিডিএফ ডাউনলোড বাটন
    st.subheader("📥 ডাউনলোড সেকশন")
    pdf_output = generate_pdf()
    st.download_button(label="📄 প্রফেশনাল পিডিএফ ডাউনলোড করুন", data=pdf_output, file_name="Daily_Business_Report.pdf", mime="application/pdf")

st.markdown("---")
st.caption("Developed for Super Tasty Food | Keshobpur, Jashore")
